//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Codigos_Actividad_Economica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Codigos_Actividad_Economica()
        {
            this.Re_Empresa_CodigosActiEconomica = new HashSet<Re_Empresa_CodigosActiEconomica>();
        }

        [Display(Name = "Actividad Economica ID")]
        public int Codigos_Actividad_Economica_Id { get; set; }

        [Display(Name = "Codigo Actividad")]
        [Required(ErrorMessage = "El campo {0} es Requerido")]
        [StringLength(10, MinimumLength = 4)]
        public string Codigo_Actividad { get; set; }

        [Display(Name = "Descripcion de la Actividad")]
        [Required(ErrorMessage = "El campo {0} es Requerido")]
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Re_Empresa_CodigosActiEconomica> Re_Empresa_CodigosActiEconomica { get; set; }
    }
}
