//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas_Prestadoras_Servicios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresas_Prestadoras_Servicios()
        {
            this.Re_Empresa_EmpresaPresServicios = new HashSet<Re_Empresa_EmpresaPresServicios>();
        }
    
        public int Empresas_Prestadoras_Servicios_Id { get; set; }
        public string Nombre_Empresa { get; set; }
        public string NIT { get; set; }
        public Nullable<int> Telefono_Fijo { get; set; }
        public Nullable<int> Telefono_Celular { get; set; }
        public string Email { get; set; }
        public string Direccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Re_Empresa_EmpresaPresServicios> Re_Empresa_EmpresaPresServicios { get; set; }
    }
}
