//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Informacion_Bancaria = new HashSet<Informacion_Bancaria>();
            this.Informacion_DIAN = new HashSet<Informacion_DIAN>();
            this.Informacion_Industria_Comercio = new HashSet<Informacion_Industria_Comercio>();
            this.Informacion_Operadores = new HashSet<Informacion_Operadores>();
            this.Re_Empresa_Cliente = new HashSet<Re_Empresa_Cliente>();
            this.Re_Empresa_CodigosActiEconomica = new HashSet<Re_Empresa_CodigosActiEconomica>();
            this.Re_Empresa_EmpresaPresServicios = new HashSet<Re_Empresa_EmpresaPresServicios>();
            this.Re_Empresa_ServiciosMensualidad = new HashSet<Re_Empresa_ServiciosMensualidad>();
            this.Re_Empresa_ServiciosPorUsuario = new HashSet<Re_Empresa_ServiciosPorUsuario>();
            this.Resolucion_Facturacion = new HashSet<Resolucion_Facturacion>();
        }

        [Display(Name ="Empresa ID")]
        public int Empresa_Id { get; set; }

        [Display(Name = "Razon Social")]
        [Required(ErrorMessage ="El campo {0} es Requerido")]
        public string Razon_Social { get; set; }

        [Display(Name ="Representante Legal")]
        public Nullable<int> Representante_Legal_Id { get; set; }

        [Display(Name = "Fecha de Registro")]
        public Nullable<System.DateTime> Fecha_Registro { get; set; }

        [Display(Name = "Fecha de Creacion")]
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }

        [Display(Name = "NIT")]
        public string NIT { get; set; }

        [Display(Name = "Direccion")]
        public string Direccion { get; set; }

        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }

        [Display(Name ="Telefono Fijo")]
        [MinLength(7,ErrorMessage ="El campo {0} Requiere minimo {1} digitos")]
        public Nullable<int> Telefono_Fijo { get; set; }

        [Display(Name = "Telefono Celular")]
        [MinLength(10, ErrorMessage = "El campo {0} Requiere minimo {1} digitos")]
        public Nullable<int> Telefono_Celular { get; set; }

        [Display(Name = "RUT")]
        public string RUT { get; set; }

        [Display(Name = "Nombre de Contacto")]
        public string Nombre_Contacto { get; set; }

        [Display(Name = "Telefono de Contacto")]
        [MinLength(7, ErrorMessage = "El campo {0} Requiere minimo {1} digitos")]
        public string Telefono_Contacto { get; set; }
    
        public virtual Representante_Legal Representante_Legal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informacion_Bancaria> Informacion_Bancaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informacion_DIAN> Informacion_DIAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informacion_Industria_Comercio> Informacion_Industria_Comercio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informacion_Operadores> Informacion_Operadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Re_Empresa_Cliente> Re_Empresa_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Re_Empresa_CodigosActiEconomica> Re_Empresa_CodigosActiEconomica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Re_Empresa_EmpresaPresServicios> Re_Empresa_EmpresaPresServicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Re_Empresa_ServiciosMensualidad> Re_Empresa_ServiciosMensualidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Re_Empresa_ServiciosPorUsuario> Re_Empresa_ServiciosPorUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resolucion_Facturacion> Resolucion_Facturacion { get; set; }
    }
}
