//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Re_Empresa_EmpresaPresServicios
    {
        public int Re_Empresa_EmpresaPresServicios_Id { get; set; }
        public Nullable<int> Empresa_Id { get; set; }
        public Nullable<int> Empresas_Prestadoras_Servicios_Id { get; set; }
        public Nullable<System.DateTime> Fecha_Contrato { get; set; }
        public Nullable<System.DateTime> Fecha_Vencimiento_Contrato { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Empresas_Prestadoras_Servicios Empresas_Prestadoras_Servicios { get; set; }
    }
}
