//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Re_Empresa_CodigosActiEconomica
    {
        public int Re_Empresa_CodigosActiEconomica_Id { get; set; }
        public Nullable<int> Empresa_Id { get; set; }
        public Nullable<int> Codigos_Actividad_Economica_Id { get; set; }
    
        public virtual Codigos_Actividad_Economica Codigos_Actividad_Economica { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
