//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resolucion_Facturacion
    {
        public int Resolucion_Facturacion_Id { get; set; }
        public Nullable<int> Empresa_Id { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Fin { get; set; }
        public string Rango_Numeracion_Inicio { get; set; }
        public string Rango_Numeracion_Fin { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
